<a href="https://colab.research.google.com/github/NguyenSang2003/Machine-Learning/blob/main/Lab1_21130512_NguyenVanSang.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Task 1.1
def number(n):
  L = []
  pos = neg = 0
  sum = 0

# Nhập mảng L với kích thước n vào.
  n = int(input("Nhập vào kích thước của mảng: "))
  for i in range(n):
    temp = int(input(f"Nhập giá trị thứ {i+1}: "))
    L.append(temp)

# In ra lớn bé trong mảng L
  print("Phần tử nhỏ nhất là " + str(min(L)))
  print("Phần tử lớn nhất là " + str(max(L)))

# Tính Tổng, tổng số + - trong L
  for i in L:
    sum = sum + i
    if(i > 0):
     pos += 1
    elif(i < 0):
     neg += 1

# In ra các kết quả
  print("Tổng các phần tử trong L: " + str(sum))
  print("Mảng L sau khi sắp xếp: " + str(sorted(L)))
  print("Có " + str(pos) +" số dương trong mảng L")
  print("Có " + str(neg) +" số âm trong mảng L")

number(3)

Nhập vào kích thước của mảng: 3
Nhập giá trị thứ 1: 2
Nhập giá trị thứ 2: 3
Nhập giá trị thứ 3: 1
Phần tử nhỏ nhất là 1
Phần tử lớn nhất là 3
Tổng các phần tử trong L: 6
Mảng L sau khi sắp xếp: [1, 2, 3]
Có 3 số dương trong mảng L
Có 0 số âm trong mảng L


In [ ]:
# task 1.2
# Tính Tích thành phần
def multiple(n):
  m = 1
  for i in range(1, n+1):
    m *= i
  return m

# Tính tổng
def Sum(n):
  s = 0
  for i in range(1, n+1):
    s += multiple(i)
  return s

# Test
temp = int(input("Enter n"))
print("Kết quả từ phép tính S(n)=1+1.2+1.2.3+…+1.2.3…n, n>0","với n là", temp,"ra",Sum(temp))

Enter n3
Kết quả từ phép tính S(n)=1+1.2+1.2.3+…+1.2.3…n, n>0 với n là 3 ra 9


In [ ]:
# task 1.3
class Account:
  def __init__(self, name: str, email: str, country: str, friends: List['Account'], posts: List['Post']):
    self.name = name
    self.email = email
    self.country = country
    self.friends = friends
    self.posts = posts

  def getMaxLikePostByFriend(self):
    max_like_post = None
    max_likes = 0

    for friend in self.friends:
        for post in friend.posts:
            if post.likes > max_likes:
                max_likes = post.likes
                max_like_post = post
    return max_like_post

class Post:
  def __init__(self, content: str, subject: str, likes: int):
    self.content = content
    self.subject = subject
    self.likes = likes

class AccountManager:
  def __init__(self, accounts: List['Account']):
    self.accounts = accounts

In [ ]:
# task 2.1
import numpy as  np

# Tạo mảng từ 10 --> 25
ori_array = np.arange(10, 26)

# Đảo ngược lại
rever_array = np.flip(ori_array)

# Test
print("Mảng gốc: ", ori_array)
print("Mảng bị đảo ngược: ", rever_array)

Mảng gốc:  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]
Mảng bị đảo ngược:  [25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
# Task 2.2
import numpy as np

# Nhập mảng vào
in_arr = np.array([1,2,3,4])

# In ra mảng gốc
print("Original array:", in_arr)

# Lặp lại mảng 2 lần
repeated_2_times = np.tile(in_arr, 2)
print("Repeating 2 times:", repeated_2_times)

# Lặp lại mảng 3 lần
repeated_3_times = np.tile(in_arr, 3)
print("Repeating 3 times:", repeated_3_times)

Original array: [1 2 3 4]
Repeating 2 times: [1 2 3 4 1 2 3 4]
Repeating 3 times: [1 2 3 4 1 2 3 4 1 2 3 4]


In [ ]:
# Task 2.3
import numpy as np

# Mảng nhận vào
inp_arr = np.array([[0.42, 0.48, 0.32], [0.74, 0.58, 0.38], [0.51, 0.34, 0.15]])

# Hiển thị mảng gốc
print("Original array:")
print(inp_arr)
print("")

# Giá trị cần so sánh và thay thế
specified_value = 0.5

# Thay thế tất cả các phần tử NHỎ hơn giá trị cần so sánh
output_array = np.where(inp_arr < specified_value, specified_value, inp_arr)

# Hiển thị mảng sau khi thay thế
print(f"Replace all elements of the original array with {specified_value} for values which are LESS than {specified_value}")
print(output_array)
print("")

# Thay thế tất cả các phần tử LỚN hơn giá trị cần so sánh
output_array = np.where(inp_arr > specified_value, specified_value, inp_arr)

# Hiển thị mảng sau khi thay thế
print(f"Replace all elements of the original array with {specified_value} for values which are GREATER than {specified_value}")
print(output_array)

Original array:
[[0.42 0.48 0.32]
 [0.74 0.58 0.38]
 [0.51 0.34 0.15]]

Replace all elements of the original array with 0.5 for values which are LESS than 0.5
[[0.5  0.5  0.5 ]
 [0.74 0.58 0.5 ]
 [0.51 0.5  0.5 ]]

Replace all elements of the original array with 0.5 for values which are GREATER than 0.5
[[0.42 0.48 0.32]
 [0.5  0.5  0.38]
 [0.5  0.34 0.15]]
